import { Navigation } from '../components/navigation'
import '../styles/globals.css'

export const metadata = {
  title: 'app in Next.js 13',
  description: 'Generated by Next.js',
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
